import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import useSWR from 'swr'
import { useRouter } from 'next/router'

const fetcher = url => fetch(url).then(r => r.json())

// first param is path of the api endpoint
// second param is the fetcher function that should execute to get the 
export default function BookDetail() {
  const router = useRouter() // gets access to our router object
  const {title} = router.query // gives access to the end of the url
  // localhost:3000/lolita -> title = "Lolita"
  const { data, error } = useSWR(`api/books/${title}`, fetcher)

  // if api encounters an error, this will render
  if (error) {
    return <Main>
      Error!
    </Main>
  }

  // if this data has not been resolved yet, this renders

  if (!data) {
    return <Main>
      loading...
    </Main>
  }

  // if data comes back as expected, this renders
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        {JSON.stringify(data)}
      </Main>
    </Container>
  )
}
