import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import useSWR from 'swr'
import BookList from '../components/BookList'

const fetcher = url => fetch(url).then(r => r.json())

// first param is path of the api endpoint
// second param is the fetcher function that should execute to get the 
export default function Home() {
  const { data, error } = useSWR('api/books', fetcher)

  // if api encounters an error, this will render
  if (error) {
    return <Main>
      Error!
    </Main>
  }

  // if this data has not been resolved yet, this renders

  if (!data) {
    return <Main>
      loading...
    </Main>
  }

  // if data comes back as expected, this renders
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1> Bettereads</h1>
        <BookList books ={data} />
      </Main>
    </Container>
  )
}
